### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by gosndka** [TheCaduceus/Microsoft-E5-Auto-Renewal#1]
Hello, what kind of variables should be given in cronjob? Especially for header and yourpassword, as the guide on readme.md is very vague
![image](https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal/assets/92586328/3fbdee4e-0b64-4a7d-9da3-41d4c411a3ad)
![image](https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal/assets/92586328/0db57e66-a2b9-4fa2-85c7-589a78ea2641)
![image](https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal/assets/92586328/e07eb74d-18ed-441a-8c0b-a51d58cf339a)

**Comment by TheCaduceus** [comment]
In header, `Content-Type` should be placed as key and `application/json` as its value.

**Comment by gosndka** [comment]
> In header, `Content-Type` should be placed as key and `application/json` as its value.

Okay and as for yourpasswordhere? webapp password or the repl account's password or the cronjob account's password @TheCaduceus

**Comment by gosndka** [comment]
@TheCaduceus what's the webapp password if we run the code from repl?
