### ISSUE TITLE
I'm still getting inactive and about to expire notifications.

### ISSUE THREAD

**Issue by Cl4ySmith** [TheCaduceus/Microsoft-E5-Auto-Renewal#18]
I've been running this task on my server for about half a month now and then the logs show:
```
{＂totalErrors＂:0,＂totalRequests＂:237,＂totalSuccess＂:115,＂version＂:2.1}
```

There are now 19 days left on the subscription and I still haven't received an email notification that the renewal was successful. Today I checked the dashboard and found an alert that I was inactive and about to expire notifications. Such as:
```
This subscription is inactive and will expire soon

Please take advantage of your free trial subscription to develop solutions for Microsoft 365.

To learn more about how you can develop Microsoft 365 solutions, see [Get started](https://learn.microsoft.com/en-us/microsoft-365/developer/).
```

I don't know what went wrong. I'm guessing I need to call more API.

**Comment by darkdex52** [comment]
> I've been running this task on my server for about half a month now and then the logs show:
> 
> ```
> {＂totalErrors＂:0,＂totalRequests＂:237,＂totalSuccess＂:115,＂version＂:2.1}
> ```
> 
> There are now 19 days left on the subscription and I still haven't received an email notification that the renewal was successful. Today I checked the dashboard and found an alert that I was inactive and about to expire notifications. Such as:
> 
> ```
> This subscription is inactive and will expire soon
> 
> Please take advantage of your free trial subscription to develop solutions for Microsoft 365.
> 
> To learn more about how you can develop Microsoft 365 solutions, see [Get started](https://learn.microsoft.com/en-us/microsoft-365/developer/).
> ```
> 
> I don't know what went wrong. I'm guessing I need to call more API.

Did you ever get renewed? I'm getting the same thing.

**Comment by Cl4ySmith** [comment]
> > I've been running this task on my server for about half a month now and then the logs show:
> > ```
> > {＂totalErrors＂:0,＂totalRequests＂:237,＂totalSuccess＂:115,＂version＂:2.1}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There are now 19 days left on the subscription and I still haven't received an email notification that the renewal was successful. Today I checked the dashboard and found an alert that I was inactive and about to expire notifications. Such as:
> > ```
> > This subscription is inactive and will expire soon
> > 
> > Please take advantage of your free trial subscription to develop solutions for Microsoft 365.
> > 
> > To learn more about how you can develop Microsoft 365 solutions, see [Get started](https://learn.microsoft.com/en-us/microsoft-365/developer/).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know what went wrong. I'm guessing I need to call more API.
> 
> Did you ever get renewed? I'm getting the same thing.

Sadly, NO! Go get another account and run for your life!

**Comment by Cl4ySmith** [comment]
> > I've been running this task on my server for about half a month now and then the logs show:
> > ```
> > {＂totalErrors＂:0,＂totalRequests＂:237,＂totalSuccess＂:115,＂version＂:2.1}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There are now 19 days left on the subscription and I still haven't received an email notification that the renewal was successful. Today I checked the dashboard and found an alert that I was inactive and about to expire notifications. Such as:
> > ```
> > This subscription is inactive and will expire soon
> > 
> > Please take advantage of your free trial subscription to develop solutions for Microsoft 365.
> > 
> > To learn more about how you can develop Microsoft 365 solutions, see [Get started](https://learn.microsoft.com/en-us/microsoft-365/developer/).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know what went wrong. I'm guessing I need to call more API.
> 
> Did you ever get renewed? I'm getting the same thing.

Oh My God! A few days after I got the expired message, I received the renewal success email!
