### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by cowcfj** [TheCaduceus/Microsoft-E5-Auto-Renewal#19]
<img width="876" alt="e5 renew 401" src="https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal/assets/7998130/3a3679fe-16f9-499e-ade1-c3ef898f92b6">

**Comment by Lagquary** [comment]
Same issue

**Comment by Lagquary** [comment]
> <img alt="e5 renew 401" width="876" src="https://private-user-images.githubusercontent.com/7998130/285860335-3a3679fe-16f9-499e-ade1-c3ef898f92b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2OTg3ODMsIm5iZiI6MTcwMjY5ODQ4MywicGF0aCI6Ii83OTk4MTMwLzI4NTg2MDMzNS0zYTM2NzlmZS0xNmY5LTQ5OWUtYWRlMS1jM2VmODk4ZjkyYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMDM0ODAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUyMGJkNTk5ZGIwYjVhNjdjYmRmOGZmNmYxZmU3NWQ2MjI2MTViMTQyMjhiMzA2ZmVmYzAzNmMwMzcyMTM1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DvtkYraq6yaJsY7neCoQuKQolqi8WCLooevVI6wQt1Y">

Do you have any way to fix ?
