### ISSUE TITLE
which account to Create an app in [Azure Active Directory]?

### ISSUE THREAD

**Issue by tino926** [TheCaduceus/Microsoft-E5-Auto-Renewal#23]
In this page https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal#variables, I saw this words:

>     CLIENT_ID|E5_CLIENT_ID: ID of your Azure Active Directory app. str
>         Create an app in [Azure Active Directory](https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/RegisteredApps).

I am not sure which account should I use to create an app.
I have three accounts now:
1. An original one (xxx@live.com). I use this to apply microsoft e5 developer
2. An admin account created when in the process when I apply microsoft e5 developer, it looks like: admin@yyy.onmicrosoft.com
3. A general user account created after I successfully applied microsoft e5 developer. it looks like: user1@yyy.onmicrosoft.com

**Comment by TheCaduceus** [comment]
Admin account.
