### ISSUE TITLE
Client ID and Client Secret don't seems to working at web UI (or maybe i'm wrong)

### ISSUE THREAD

**Issue by ThisisZeth** [TheCaduceus/Microsoft-E5-Auto-Renewal#25]
Hello. I need help about the public instance for web UI (https://e5.thecaduceus.eu.org). I've been trying to renew my E5 but no luck, but this web UI gives me a hope to do it. I have an admin account which I can control over children accounts inside my domain, but I got a message telling that the trial subscription is about to end. I did followed [these steps](https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal?tab=readme-ov-file#variables) and finally retrieved both Client ID and Client Secret, but when I put these into the website, it just refresh the page with nothing happened. I'm kinda curious of the steps since I'm very very new to this with no coding experience. Please help me out for this. Thank you <3

**Comment by TheCaduceus** [comment]
Failed to reproduce, possibly user side issue.
