### ISSUE TITLE
Headers in cronjob?

### ISSUE THREAD

**Issue by undeadmecha0** [TheCaduceus/Microsoft-E5-Auto-Renewal#28]
![Screenshot_20241223-163655_Brave](https://github.com/user-attachments/assets/0a6ffb46-846a-4dc6-aa75-19e47a6fd165)
![Screenshot_20241223-163746_Brave](https://github.com/user-attachments/assets/2e1dfceb-bebd-4e55-a22b-e6c50bbde2db)

How do i input this in cronjob?

**Comment by TheCaduceus** [comment]
Refer to issue https://github.com/TheCaduceus/Microsoft-E5-Auto-Renewal/issues/1.
