### ISSUE TITLE
Question about webpassword

### ISSUE THREAD

**Issue by gosndka** [TheCaduceus/Microsoft-E5-Auto-Renewal#4]
What's the webpassword if we run the code on repl?

**Comment by k4am-n0sxtra** [comment]
Webpassword is mainly used to get the Logs

Eg URL:
https://username.repl.co/logs?password=(password)

**Comment by gosndka** [comment]
> Webpassword is mainly used to get the Logs
> 
> Eg URL: https://username.repl.co/logs?password=(password)

so it can be anything? then

**Comment by SumitSain67** [comment]
@k4am-n0sxtra It is required to use /call route of web server as well otherwise anyone can spam your Microsoft account by sending tons of requests to /call, that's why server ask you for your password to make sure it's really you.
